USE [master]
GO

/****** Object:  Database [ResourceForecast]    Script Date: 7/2/2016 6:52:05 PM ******/
CREATE DATABASE [ResourceForecast]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ResourceForecast', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS2014\MSSQL\DATA\ResourceForecast.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ResourceForecast_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS2014\MSSQL\DATA\ResourceForecast_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ResourceForecast] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ResourceForecast].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ResourceForecast] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ResourceForecast] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ResourceForecast] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ResourceForecast] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ResourceForecast] SET ARITHABORT OFF 
GO

ALTER DATABASE [ResourceForecast] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ResourceForecast] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ResourceForecast] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ResourceForecast] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ResourceForecast] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ResourceForecast] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ResourceForecast] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ResourceForecast] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ResourceForecast] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ResourceForecast] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ResourceForecast] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ResourceForecast] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ResourceForecast] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ResourceForecast] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ResourceForecast] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ResourceForecast] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ResourceForecast] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ResourceForecast] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ResourceForecast] SET  MULTI_USER 
GO

ALTER DATABASE [ResourceForecast] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ResourceForecast] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ResourceForecast] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ResourceForecast] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ResourceForecast] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ResourceForecast] SET  READ_WRITE 
GO


